### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by alliza** [bsylve1996/CSC_3380_Dream_Team#1]
Implementing an integrated login system with google, Facebook..

**Comment by Lunsluns** [comment]
This is in the lun_calendar branch for the google login. If you want to look at the file it's in, it's in index.html to write for the login. There are a couple of things that need to be there, but here's the client id. I'll work on adding you to the google dev

  <meta name= "google-signin-client_id" content="schedulr-195523" >

**Comment by alliza** [comment]
Login system works Now
